pattern_cols: 10
pattern_rows: 8
center_distance_mm: 15

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_matrix: [1768.9783970591777, 0, 730.86444391371003, 0, 1764.4491036536815, 591.18424419341113, 0, 0, 1]
distort_coeffs: [-0.12859058510214097, 0.25462974046259212, 0.00050780540845081837, -0.00069923115497245211, -0.90843470148160643]

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"
